# # config file for prometheus

# # global config
# global:
#   scrape_interval: 20s
#   scrape_timeout: 15s
#   evaluation_interval: 10s
# alerting:
#   alertmanagers:
#   - follow_redirects: true
#     enable_http2: true
#     scheme: http
#     timeout: 10s
#     api_version: v2
#     static_configs:
#     - targets: []
# scrape_configs:
# - job_name: prometheus
#   honor_timestamps: true
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   metrics_path: /metrics
#   scheme: http
#   follow_redirects: true
#   enable_http2: true
#   static_configs:
#   - targets:
#     - localhost:9090
# - job_name: 'fastapi'
#   scrape_interval: 10s
#   metrics_path: /metrics
#   static_configs:
#     - targets: ['web:8000']

# Custom monitoring configuration file
global:
  scrape_interval: 5s  
  scrape_timeout: 10s   
  evaluation_interval: 5s  

alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []

scrape_configs:
  # Prometheus server scraping
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 20s  
  scrape_timeout: 15s  
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090

- job_name: 'fast_api'
  scrape_interval: 5s  
  metrics_path: /metrics  
  static_configs:
  - targets:
    - web:8000  
